---
- include: bootstrap.yml
  when: inventory_hostname in groups['hyperv']

- include: config.yml
  when: inventory_hostname in groups['hyperv']

- include: start.yml
  when: inventory_hostname in groups['hyperv']
